###########
# TEMPLATE 
# 1. Pull python base image
# 2. Set a working directory for Docker images, and set default python env vars
# 3. Upgrade pip just in case
# 4. Copy all files [or select files] to the working directory
# 5. Install dependencies and [optionally] run scripts
###########

# pull official base image
FROM python:3.9.5-slim-buster

# set work directory
WORKDIR /flask_app

# set environment variables - prevents the creation of pyc and buffering to stdout and stderr
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# upgrade pip just to be safe
RUN pip install --upgrade pip

# copy over local from editor to Docker workdir
COPY . /flask_app

# addresses psycopg installation error: https://stackoverflow.com/questions/62715570/failing-to-install-psycopg2-binary-on-new-docker-container
# [IMPORANT] - another solution is to install psycopg-binary instead
# RUN apt-get update \
#     && apt-get -y install libpq-dev gcc \
#     && pip install psycopg2

# run installation
RUN pip install -r requirements.txt